// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgzfggjenvqtynfyqtzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnemZnZ2plbnZxdHluZnlxdHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTA5MjcsImV4cCI6MjA2MTE4NjkyN30.WlbTb1bsz-jJieTfWdRol6zHuTbngSPAHRhD9rAj7y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);